
package br.com.carlosenzo.telas;

import br.com.carlosenzo.classes.Usuario;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class InicialCliente extends javax.swing.JFrame {

    private Usuario user;
    private FileInputStream fis;
    
    public InicialCliente() {
        initComponents();
        ColocarIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imagePerfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        btnEnviarModelo = new javax.swing.JButton();
        btnAnalizarModelos = new javax.swing.JButton();
        btnComprarModelo = new javax.swing.JButton();
        btnConfigPerfil = new javax.swing.JButton();
        btnSobreEmpresa = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C&E Invenções 3D (Inicial-Cliente)");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 50));

        jPanel1.setBackground(new java.awt.Color(70, 62, 49));

        jPanel2.setBackground(new java.awt.Color(155, 132, 105));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(155, 132, 105));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(112, 107, 79));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        imagePerfil.setBackground(new java.awt.Color(255, 255, 255));
        imagePerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 132, 105), 5));
        imagePerfil.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 206, 188));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem-vindo ao sistema");

        labelCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(221, 206, 188));
        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCliente.setText("\"Cliente\"");

        label.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        label.setForeground(new java.awt.Color(221, 206, 188));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("O que deseja fazer?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imagePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(labelCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imagePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(labelCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label)
                .addContainerGap())
        );

        btnEnviarModelo.setBackground(new java.awt.Color(120, 112, 87));
        btnEnviarModelo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEnviarModelo.setForeground(new java.awt.Color(232, 221, 164));
        btnEnviarModelo.setText("Enviar Modelo");
        btnEnviarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarModeloActionPerformed(evt);
            }
        });

        btnAnalizarModelos.setBackground(new java.awt.Color(120, 112, 87));
        btnAnalizarModelos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAnalizarModelos.setForeground(new java.awt.Color(232, 221, 164));
        btnAnalizarModelos.setText("Analizar Modelos");
        btnAnalizarModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarModelosActionPerformed(evt);
            }
        });

        btnComprarModelo.setBackground(new java.awt.Color(120, 112, 87));
        btnComprarModelo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnComprarModelo.setForeground(new java.awt.Color(232, 221, 164));
        btnComprarModelo.setText("Comprar Modelos");
        btnComprarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarModeloActionPerformed(evt);
            }
        });

        btnConfigPerfil.setBackground(new java.awt.Color(120, 112, 87));
        btnConfigPerfil.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfigPerfil.setForeground(new java.awt.Color(232, 221, 164));
        btnConfigPerfil.setText("Configurar Perfil");
        btnConfigPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigPerfilActionPerformed(evt);
            }
        });

        btnSobreEmpresa.setBackground(new java.awt.Color(120, 112, 87));
        btnSobreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSobreEmpresa.setForeground(new java.awt.Color(232, 221, 164));
        btnSobreEmpresa.setText("Sobre a Empresa");
        btnSobreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreEmpresaActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(120, 112, 87));
        btnSair.setForeground(new java.awt.Color(232, 221, 164));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnalizarModelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComprarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfigPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSobreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnalizarModelos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComprarModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfigPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Sair();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConfigPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigPerfilActionPerformed
        OpenConfigPro();
    }//GEN-LAST:event_btnConfigPerfilActionPerformed

    private void btnEnviarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarModeloActionPerformed
        EnviarModelo();
    }//GEN-LAST:event_btnEnviarModeloActionPerformed

    private void btnAnalizarModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarModelosActionPerformed
        OpenAnalizarModelo();
    }//GEN-LAST:event_btnAnalizarModelosActionPerformed

    private void btnComprarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarModeloActionPerformed
        JOptionPane.showMessageDialog(null, "Este botão funcionará em breve.");
    }//GEN-LAST:event_btnComprarModeloActionPerformed

    private void btnSobreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreEmpresaActionPerformed
        JOptionPane.showMessageDialog(null, "Este botão funcionará em breve.");
    }//GEN-LAST:event_btnSobreEmpresaActionPerformed

    public Usuario getUser(){
        return user;
    }
    
    public FileInputStream getFis(){
        return fis;
    }
    
    public void setUser(Usuario user){
        this.user = user;
    }
    
    public void setFis(FileInputStream fis){
        this.fis = fis;
    }
    
    public void OpenConfigPro(){
        dispose();
        ConfigurarPerfilCliente tela = new ConfigurarPerfilCliente();
        tela.abrirConfigPerfil(tela, getUser());
    }
    
    public void OpenAnalizarModelo(){
        dispose();
        Carregando tela = new Carregando();
        tela.CarregandoTabela(tela, getUser());
    }
    
    public void EnviarModelo(){
        JFileChooser jfc = escolherArquivo();
        int resultado = jfc.showOpenDialog(this);
        if(resultado == JFileChooser.APPROVE_OPTION){
            try{
                
                setFis(new FileInputStream(jfc.getSelectedFile()));
                String mens = JOptionPane.showInputDialog("Escreve uma mensagem curta:");
                String nametipo = jfc.getSelectedFile().getName();
                String tipo = nametipo.substring(nametipo.lastIndexOf("."));
                if(mens != null && !mens.isEmpty()){
                    Carregando tela = new Carregando();
                    tela.CriandoModelo(tela, getUser().getId(), mens, getFis(),tipo);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Houve um erro ao enviar! " + e.getMessage() + ".");
            }
        }
    }
    
    public JFileChooser escolherArquivo(){
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecionar arquivo");
        jfc.setFileFilter(new FileNameExtensionFilter("Arquivos (*.PDF,*.STL,*.PNG,*.JPG,*.JPEG)","pdf", "stl", "png", "jpg", "jpeg"));
        return jfc;
    }
    
    public void Sair(){
        dispose();
        Login telaLog = new Login();
        telaLog.setVisible(true);
    }
    
    public void ColocarIcone(){
        String caminho = "/image/logo.jpg";
        InputStream pasta = getClass().getResourceAsStream(caminho);
        try{
            if( pasta != null){
                Image imagem = new ImageIcon(ImageIO.read(pasta)).getImage();
                this.setIconImage(imagem);
            }else{
                System.out.println("Imagem Nao encontrado!");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public ImageIcon converterByteEmImage(byte[] image){
        try{
            ByteArrayInputStream bis = new ByteArrayInputStream(image);
            BufferedImage bufferedImage = ImageIO.read(bis);
            Image imagemScale = bufferedImage.getScaledInstance(imagePerfil.getWidth(), imagePerfil.getHeight(), Image.SCALE_SMOOTH);
            return new ImageIcon(imagemScale);
        }catch(Exception e){
            return null;
        }
    }
    
    public void AbrirClienteInicial(InicialCliente tela, Usuario user){
        tela.setVisible(true);
        labelCliente.setText(user.getNome() + "!");
        ImageIcon imageP = converterByteEmImage(user.getImagem());
        imagePerfil.setIcon(imageP);
        setUser(user);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarModelos;
    private javax.swing.JButton btnComprarModelo;
    private javax.swing.JButton btnConfigPerfil;
    private javax.swing.JButton btnEnviarModelo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSobreEmpresa;
    private javax.swing.JLabel imagePerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelCliente;
    // End of variables declaration//GEN-END:variables
}
